apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 2
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: shaddev/udagram-frontend:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports: 
        - containerPort: 80