apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      run: user
  replicas: 2
  template:
    metadata:
      labels:
        run: user
    spec:
      restartPolicy: Always
      containers:
      - name: user
        image: shaddev/udagram-api-user:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret